#### PONG
GET {{host}}/auth/ping
Authorization: Bearer {{token}}

#### CAMBIAR CONTRASEÑA
POST {{host}}/auth/password
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "newPassword": "{{password}}",
  "oldPassword": "{{password}}"
}

#### ASIGNARSE SECCIÓN
POST {{host}}/auth/seccion
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "seccionesId": ["4", "5"]
}

#### SECCIONES ASIGNADAS
GET {{host}}/auth/seccion
Authorization: Bearer {{token}}

#### ASIGNARSE HOBBIES
POST {{host}}/auth/hobby
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "hobbyId": "1"
}

#### INFORMACIÓN DE PERFIL
GET {{host}}/auth/profile
Authorization: Bearer {{token}}

#### SEND A FRIEND REQUEST
POST {{host}}/auth/friends/sendRequest
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "carne": "19943"
}

#### ACCEPT A FRIEND REQUEST
POST {{host}}/auth/friends/acceptRequest
Authorization: Bearer {{token}}
Content-Type: application/json

# Usuario que envió la request
{
  "carne": "0"
}

#### CANCEL REQUEST
POST {{host}}/auth/friends/cancelRequest
Authorization: Bearer {{token}}
Content-Type: application/json

# Usuario que envió/recibió la request
{
  "carne": "0"
}


#### SEND A FRIEND REQUEST
GET {{host}}/auth/friends/getFriends
Authorization: Bearer {{token}}

#### OBTAIN THE RECEIVED FRIENDSHIP REQUESTS
GET {{host}}/auth/friends/receivedRequests
Authorization: Bearer {{token}}

#### OBTAIN THE SENT FRIENDSHIP REQUESTS
GET {{host}}/auth/friends/sentRequests
Authorization: Bearer {{token}}

#### PARA REPORTAR UN USUARIO
POST {{host}}/auth/report
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "reported": "0",
  "reason": "ser mala onda D:"
}
