#### BY COMMON SECTIONS
GET {{host}}/auth/suggestions/courses
Authorization: Bearer {{token}}
Accept: application/json

### BY COMMON HOBBIES
GET {{host}}/auth/suggestions/hobbies
Authorization: Bearer {{token}}
Accept: application/json

### BY FRIENDS OF MY FRIENDS
GET {{host}}/auth/suggestions/friends
Authorization: Bearer {{token}}
Accept: application/json
