#### BY COMMON SECTIONS
GET {{host}}/auth/suggestions/courses
Authorization: Bearer {{token}}
Accept: application/json

### BY COMMON HOBBIES
GET {{host}}/auth/suggestions/hobbies
Authorization: Bearer {{token}}
Accept: application/json
