#### PETICIÓN DE RESETEAR LA CONTRASEÑA
POST {{host}}/request/passwordReset
Content-Type: application/json

{
  "carne": "0"
}

#### ACEPTAR PETICIÓN PARA RESETEAR LA CONTRASEÑA
POST {{host}}/request/acceptPasswordReset
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "newPassword": "{{password}}"
}
