#### PETICIÓN DE RESETEAR LA CONTRASEÑA
POST {{host}}/request/passwordReset
Content-Type: application/json

{
  "carne": "0"
}

#### ACEPTAR PETICIÓN PARA RESETEAR LA CONTRASEÑA
POST {{host}}/request/acceptPasswordReset
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "newPassword": "{{password}}"
}

#### SIGN UP REQUEST
POST {{host}}/request/signup
Content-Type: application/json

{
  "carne": "{{carne}}",
  "nombre": "Pepe",
  "apellido": "Mario",
  "carreraId": "1",
  "password": "{{password}}",
  "correo": "{{correo}}"
}

#### ACCEPT SIGN UP REQUEST
POST {{host}}/request/acceptSignUp
Authorization: Bearer token
