name: Meeting Backend CI-CD

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: node:14-alpine

    services:
      postgres:
        image: postgres:alpine
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - name: Copying the Source Code
        uses: actions/checkout@v2
        with:
          ref: prod

      - name: Installing postgres client
        run: |
          apt-get update
          apt-get install --yes postgresql-client

      - name: Running setup.sql
        run: psql -d postgres -h postgres -U postgres -f ./setup/setup.sql
        env:
          PASSWORD: postgres

      - name: Running stored_procedures.sql
        run: psql -h postgres -f ./setup/stored_procedures.sql
        env:
          PASSWORD: postgres

      - name: Running views.sql
        run: psql -h postgres -f ./setup/views.sql
        env:
          PASSWORD: postgres

      - name: Instaling Libraries
        run: npm install

      - name: Running tests
        run: npm run test
        env:
          # Con el resto de variables el valor default basta o no son necesarias
          ENVIRONMENT: testing
          DATABASE_HOST: postgres
