name: Backend Deployment

on:
  push:
    branches:
      - prod

jobs:
  publish-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest,${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}

    deploy:
      runs-on: ubuntu-latest
      needs: publish-docker

      steps:
        - name: Pull and Run Docker Image
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            script: |
              # stop old container
              docker stop backend
              # pull new image
              docker run -d -it --rm                 \
              -p 3000:3000                           \
              -e "DATABASE_PASSWORD=$(cat password)" \
              -e "DATABASE_HOST=$(cat database)"     \
              --name backend                         \
              ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}
