name: Meeting Backend CI-CD

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      # psql
      PGPASSWORD: postgres
      PGHOST: postgres@localhost
      PGDATABASE: postgres

      # para la imagen de docker
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres


    services:
      postgres:
        image: postgres:alpine
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Copying the Source Code
        uses: actions/checkout@v2
        with:
          ref: prod

      - name: Creating tables
        run: psql -f ./setup/setup.sql

      - name: Creating Stored Procedures
        run: psql -f ./setup/stored_procedures.sql

      - name: Creating Views
        run: psql -f ./setup/views.sql

      - name: Setup node environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Instaling Libraries
        run: npm install

      - name: Running tests
        run: npm run test
        env:
          # Con el resto de variables de entorno el valor default basta o no son necesarias
          ENVIRONMENT: testing
